component_depth: 1
languages:
- java
exclude:
- ./bin/.*
- ./bin/org/.*
- ./bin/org/apache/.*
- ./bin/org/apache/tapestry/.*
- ./bin/org/apache/tapestry/mojo/.*
- ./bin/org/apache/tapestry5/.*
- ./bin/org/apache/tapestry5/ajax/.*
- ./bin/org/apache/tapestry5/annotations/.*
- ./bin/org/apache/tapestry5/beaneditor/.*
- ./bin/org/apache/tapestry5/corelib/.*
- ./bin/org/apache/tapestry5/corelib/base/.*
- ./bin/org/apache/tapestry5/corelib/components/.*
- ./bin/org/apache/tapestry5/corelib/data/.*
- ./bin/org/apache/tapestry5/corelib/internal/.*
- ./bin/org/apache/tapestry5/corelib/mixins/.*
- ./bin/org/apache/tapestry5/corelib/pages/.*
- ./bin/org/apache/tapestry5/dom/.*
- ./bin/org/apache/tapestry5/grid/.*
- ./bin/org/apache/tapestry5/hibernate/.*
- ./bin/org/apache/tapestry5/hibernate/annotations/.*
- ./bin/org/apache/tapestry5/hibernate/pages/.*
- ./bin/org/apache/tapestry5/integration/.*
- ./bin/org/apache/tapestry5/integration/app0/.*
- ./bin/org/apache/tapestry5/integration/app0/services/.*
- ./bin/org/apache/tapestry5/integration/app1/.*
- ./bin/org/apache/tapestry5/integration/app1/base/.*
- ./bin/org/apache/tapestry5/integration/app1/components/.*
- ./bin/org/apache/tapestry5/integration/app1/data/.*
- ./bin/org/apache/tapestry5/integration/app1/mixins/.*
- ./bin/org/apache/tapestry5/integration/app1/pages/.*
- ./bin/org/apache/tapestry5/integration/app1/pages/music/.*
- ./bin/org/apache/tapestry5/integration/app1/pages/nested/.*
- ./bin/org/apache/tapestry5/integration/app1/services/.*
- ./bin/org/apache/tapestry5/integration/app2/.*
- ./bin/org/apache/tapestry5/integration/app2/components/.*
- ./bin/org/apache/tapestry5/integration/app2/mixins/.*
- ./bin/org/apache/tapestry5/integration/app2/pages/.*
- ./bin/org/apache/tapestry5/integration/app2/services/.*
- ./bin/org/apache/tapestry5/integration/app3/.*
- ./bin/org/apache/tapestry5/integration/app3/pages/.*
- ./bin/org/apache/tapestry5/integration/app3/services/.*
- ./bin/org/apache/tapestry5/integration/app4/.*
- ./bin/org/apache/tapestry5/integration/app4/pages/.*
- ./bin/org/apache/tapestry5/integration/app4/services/.*
- ./bin/org/apache/tapestry5/integration/app5/.*
- ./bin/org/apache/tapestry5/integration/app5/pages/.*
- ./bin/org/apache/tapestry5/integration/app5/services/.*
- ./bin/org/apache/tapestry5/integration/pagelevel/.*
- ./bin/org/apache/tapestry5/integration/reload/.*
- ./bin/org/apache/tapestry5/integration/reload/services/.*
- ./bin/org/apache/tapestry5/internal/.*
- ./bin/org/apache/tapestry5/internal/antlr/.*
- ./bin/org/apache/tapestry5/internal/beaneditor/.*
- ./bin/org/apache/tapestry5/internal/bindings/.*
- ./bin/org/apache/tapestry5/internal/event/.*
- ./bin/org/apache/tapestry5/internal/events/.*
- ./bin/org/apache/tapestry5/internal/grid/.*
- ./bin/org/apache/tapestry5/internal/gzip/.*
- ./bin/org/apache/tapestry5/internal/hibernate/.*
- ./bin/org/apache/tapestry5/internal/model/.*
- ./bin/org/apache/tapestry5/internal/pageload/.*
- ./bin/org/apache/tapestry5/internal/parser/.*
- ./bin/org/apache/tapestry5/internal/renderers/.*
- ./bin/org/apache/tapestry5/internal/services/.*
- ./bin/org/apache/tapestry5/internal/spring/.*
- ./bin/org/apache/tapestry5/internal/structure/.*
- ./bin/org/apache/tapestry5/internal/test/.*
- ./bin/org/apache/tapestry5/internal/transform/.*
- ./bin/org/apache/tapestry5/internal/transform/components/.*
- ./bin/org/apache/tapestry5/internal/transform/pages/.*
- ./bin/org/apache/tapestry5/internal/translator/.*
- ./bin/org/apache/tapestry5/internal/util/.*
- ./bin/org/apache/tapestry5/ioc/.*
- ./bin/org/apache/tapestry5/ioc/annotations/.*
- ./bin/org/apache/tapestry5/ioc/def/.*
- ./bin/org/apache/tapestry5/ioc/internal/.*
- ./bin/org/apache/tapestry5/ioc/internal/services/.*
- ./bin/org/apache/tapestry5/ioc/internal/util/.*
- ./bin/org/apache/tapestry5/ioc/services/.*
- ./bin/org/apache/tapestry5/ioc/test/.*
- ./bin/org/apache/tapestry5/ioc/util/.*
- ./bin/org/apache/tapestry5/json/.*
- ./bin/org/apache/tapestry5/model/.*
- ./bin/org/apache/tapestry5/runtime/.*
- ./bin/org/apache/tapestry5/services/.*
- ./bin/org/apache/tapestry5/services/ajax/.*
- ./bin/org/apache/tapestry5/spring/.*
- ./bin/org/apache/tapestry5/test/.*
- ./bin/org/apache/tapestry5/tutorial/.*
- ./bin/org/apache/tapestry5/tutorial/data/.*
- ./bin/org/apache/tapestry5/tutorial/entities/.*
- ./bin/org/apache/tapestry5/tutorial/pages/.*
- ./bin/org/apache/tapestry5/tutorial/pages/address/.*
- ./bin/org/apache/tapestry5/tutorial/services/.*
- ./bin/org/apache/tapestry5/upload/.*
- ./bin/org/apache/tapestry5/upload/components/.*
- ./bin/org/apache/tapestry5/upload/integration/.*
- ./bin/org/apache/tapestry5/upload/internal/.*
- ./bin/org/apache/tapestry5/upload/internal/services/.*
- ./bin/org/apache/tapestry5/upload/services/.*
- ./bin/org/apache/tapestry5/urlrewriter/.*
- ./bin/org/apache/tapestry5/util/.*
- ./bin/org/apache/tapestry5/validator/.*
- ./bin/org/example/.*
- ./bin/org/example/app0/.*
- ./bin/org/example/app0/entities/.*
- ./bin/org/example/testapp/.*
- ./bin/org/example/testapp/pages/.*
- ./bin/org/example/testapp/services/.*
- ./bin/org/example/upload/.*
- ./bin/org/example/upload/base/.*
- ./bin/org/example/upload/pages/.*
- ./bin/org/example/upload/services/.*
- ./lib/.*
- ./quickstart/.*
- ./tapestry-annotations/.*
- ./tapestry-component-report/.*
- ./tapestry-core/.*
- ./tapestry-hibernate/.*
- ./tapestry-hibernate-core/.*
- ./tapestry-ioc/.*
- ./tapestry-project/.*
- ./tapestry-spring/.*
- ./tapestry-test/.*
- ./tapestry-tutorial1/.*
- ./tapestry-upload/.*
